In [1]:
#Importinng neccesaary librarys
import pandas as pd
import numpy as np 
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge,Lasso,LassoCV,RidgeCV,ElasticNet,ElasticNetCV,LinearRegression
from sklearn.model_selection import train_test_split
import statsmodels.api as an
import matplotlib.pyplot as plt
import seaborn as sns
from pandas_profiling import ProfileReport
import pickle

In [2]:
df = pd.read_csv('Admission_prediction.csv')    #Data Injection

In [3]:
df

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  \
0             1      337.0        118.0                4.0  4.5  4.5  9.65   
1             2      324.0        107.0                4.0  4.0  4.5  8.87   
2             3        NaN        104.0                3.0  3.0  3.5  8.00   
3             4      322.0        110.0                3.0  3.5  2.5  8.67   
4             5      314.0        103.0                2.0  2.0  3.0  8.21   
..          ...        ...          ...                ...  ...  ...   ...   
495         496      332.0        108.0                5.0  4.5  4.0  9.02   
496         497      337.0        117.0                5.0  5.0  5.0  9.87   
497         498      330.0        120.0                5.0  4.5  5.0  9.56   
498         499      312.0        103.0                4.0  4.0  5.0  8.43   
499         500      327.0        113.0                4.0  4.5  4.5  9.04   

     Research  Chance of Admit  
0           1             0.92  
1           1             0.76  
2           1             0.72  
3           1             0.80  
4           0             0.65  
..        ...              ...  
495         1             0.87  
496         1             0.96  
497         1             0.93  
498         0             0.73  
499         0             0.84  

[500 rows x 9 columns]

In [4]:
df.describe()

Serial No.   GRE Score  TOEFL Score  University Rating         SOP  \
count  500.000000  485.000000   490.000000         485.000000  500.000000   
mean   250.500000  316.558763   107.187755           3.121649    3.374000   
std    144.481833   11.274704     6.112899           1.146160    0.991004   
min      1.000000  290.000000    92.000000           1.000000    1.000000   
25%    125.750000  308.000000   103.000000           2.000000    2.500000   
50%    250.500000  317.000000   107.000000           3.000000    3.500000   
75%    375.250000  325.000000   112.000000           4.000000    4.000000   
max    500.000000  340.000000   120.000000           5.000000    5.000000   

             LOR        CGPA    Research  Chance of Admit  
count  500.00000  500.000000  500.000000        500.00000  
mean     3.48400    8.576440    0.560000          0.72174  
std      0.92545    0.604813    0.496884          0.14114  
min      1.00000    6.800000    0.000000          0.34000  
25%      3.00000    8.127500    0.000000          0.63000  
50%      3.50000    8.560000    1.000000          0.72000  
75%      4.00000    9.040000    1.000000          0.82000  
max      5.00000    9.920000    1.000000          0.97000

In [5]:
pf=ProfileReport(df)     #Auto EDA library

In [6]:
pf.to_widgets()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [7]:
df.isnull().sum()

Serial No.            0
GRE Score            15
TOEFL Score          10
University Rating    15
SOP                   0
LOR                   0
CGPA                  0
Research              0
Chance of Admit       0
dtype: int64

In [8]:
df['GRE Score'] = df['GRE Score'].fillna(df['GRE Score'].mean())     # filling NAN with mean

In [9]:
df['TOEFL Score'] = df['TOEFL Score'].fillna(df['TOEFL Score'].mean())

In [10]:
df['University Rating'] = df['University Rating'].fillna(df['University Rating'].mean())

In [11]:
df.isnull().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [12]:
df.drop(columns=['Serial No.'],inplace=True)         # dropping unneccesaary features

In [13]:
y =df['Chance of Admit']          #Dependent
y 

0      0.92
1      0.76
2      0.72
3      0.80
4      0.65
       ... 
495    0.87
496    0.96
497    0.93
498    0.73
499    0.84
Name: Chance of Admit, Length: 500, dtype: float64

In [14]:
x = df.drop(columns=['Chance of Admit'])      #Independent
x

GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  Research
0    337.000000        118.0                4.0  4.5  4.5  9.65         1
1    324.000000        107.0                4.0  4.0  4.5  8.87         1
2    316.558763        104.0                3.0  3.0  3.5  8.00         1
3    322.000000        110.0                3.0  3.5  2.5  8.67         1
4    314.000000        103.0                2.0  2.0  3.0  8.21         0
..          ...          ...                ...  ...  ...   ...       ...
495  332.000000        108.0                5.0  4.5  4.0  9.02         1
496  337.000000        117.0                5.0  5.0  5.0  9.87         1
497  330.000000        120.0                5.0  4.5  5.0  9.56         1
498  312.000000        103.0                4.0  4.0  5.0  8.43         0
499  327.000000        113.0                4.0  4.5  4.5  9.04         0

[500 rows x 7 columns]

In [15]:
scaler = StandardScaler()            #convert to standard form 

In [16]:
arr = scaler.fit_transform(x)

In [17]:
arr

array([[ 1.84274116e+00,  1.78854223e+00,  7.78905651e-01, ...,
         1.09894429e+00,  1.77680627e+00,  8.86405260e-01],
       [ 6.70814288e-01, -3.10581135e-02,  7.78905651e-01, ...,
         1.09894429e+00,  4.85859428e-01,  8.86405260e-01],
       [ 5.12433309e-15, -5.27312752e-01, -1.07876604e-01, ...,
         1.73062093e-02, -9.54042814e-01,  8.86405260e-01],
       ...,
       [ 1.21170361e+00,  2.11937866e+00,  1.66568791e+00, ...,
         1.63976333e+00,  1.62785086e+00,  8.86405260e-01],
       [-4.10964364e-01, -6.92730965e-01,  7.78905651e-01, ...,
         1.63976333e+00, -2.42366993e-01, -1.12815215e+00],
       [ 9.41258951e-01,  9.61451165e-01,  7.78905651e-01, ...,
         1.09894429e+00,  7.67219636e-01, -1.12815215e+00]])

In [18]:
df1 = pd.DataFrame(arr)

In [19]:
df1

0         1         2         3         4         5         6
0    1.842741e+00  1.788542  0.778906  1.137360  1.098944  1.776806  0.886405
1    6.708143e-01 -0.031058  0.778906  0.632315  1.098944  0.485859  0.886405
2    5.124333e-15 -0.527313 -0.107877 -0.377773  0.017306 -0.954043  0.886405
3    4.905178e-01  0.465197 -0.107877  0.127271 -1.064332  0.154847  0.886405
4   -2.306679e-01 -0.692731 -0.994659 -1.387862 -0.523513 -0.606480 -1.128152
..            ...       ...       ...       ...       ...       ...       ...
495  1.392000e+00  0.134360  1.665688  1.137360  0.558125  0.734118  0.886405
496  1.842741e+00  1.623124  1.665688  1.642404  1.639763  2.140919  0.886405
497  1.211704e+00  2.119379  1.665688  1.137360  1.639763  1.627851  0.886405
498 -4.109644e-01 -0.692731  0.778906  0.632315  1.639763 -0.242367 -1.128152
499  9.412590e-01  0.961451  0.778906  1.137360  1.098944  0.767220 -1.128152

[500 rows x 7 columns]

VIF

In [20]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
vif_df = pd.DataFrame()               #check multicolenerity

In [21]:
vif_df['vif']=[variance_inflation_factor(arr,i) for i in range(arr.shape[1])]


In [22]:
vif_df['feature'] = x.columns

In [23]:
vif_df

vif            feature
0  4.153268          GRE Score
1  3.792866        TOEFL Score
2  2.508768  University Rating
3  2.775750                SOP
4  2.037308                LOR
5  4.651670               CGPA
6  1.459311           Research

data seperation

In [24]:
x_train,x_test,y_train,y_test = train_test_split(arr,y,test_size=.25)

In [25]:
x_train

array([[ 1.93288938,  1.29228759,  1.66568791, ...,  1.63976333,
         1.08168105,  0.88640526],
       [ 0.58066607,  0.96145116, -0.1078766 , ..., -0.52351283,
         1.23063645,  0.88640526],
       [ 1.48214828,  1.95396044,  1.66568791, ...,  1.09894429,
         1.99196407,  0.88640526],
       ...,
       [ 1.5722965 ,  1.4577058 ,  0.77890565, ..., -0.52351283,
        -0.95404281,  0.88640526],
       [ 0.40036962,  0.29977831, -0.1078766 , ..., -0.52351283,
        -0.06031039,  0.88640526],
       [ 1.75259294,  0.79603295,  1.66568791, ...,  1.63976333,
         1.95886287,  0.88640526]])

Model_1

In [26]:
lr = LinearRegression()

In [27]:
lr.fit(x_train,y_train)

LinearRegression()

In [28]:
pickle.dump(lr,open('Admission_lr_model.pickle','wb'))     # Store train model

In [29]:
df

GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  Research  \
0    337.000000        118.0                4.0  4.5  4.5  9.65         1   
1    324.000000        107.0                4.0  4.0  4.5  8.87         1   
2    316.558763        104.0                3.0  3.0  3.5  8.00         1   
3    322.000000        110.0                3.0  3.5  2.5  8.67         1   
4    314.000000        103.0                2.0  2.0  3.0  8.21         0   
..          ...          ...                ...  ...  ...   ...       ...   
495  332.000000        108.0                5.0  4.5  4.0  9.02         1   
496  337.000000        117.0                5.0  5.0  5.0  9.87         1   
497  330.000000        120.0                5.0  4.5  5.0  9.56         1   
498  312.000000        103.0                4.0  4.0  5.0  8.43         0   
499  327.000000        113.0                4.0  4.5  4.5  9.04         0   

     Chance of Admit  
0               0.92  
1               0.76  
2               0.72  
3               0.80  
4               0.65  
..               ...  
495             0.87  
496             0.96  
497             0.93  
498             0.73  
499             0.84  

[500 rows x 8 columns]

In [30]:
test1 = scaler.transform([[337.000000,118.0,4.0,4.5,4.5,9.65,1]])

In [31]:
lr.predict(test1)

array([0.95126452])

In [32]:
model = pickle.load(open('admission_lr_model.pickle','rb'))

In [33]:
model.predict(test1)

array([0.95126452])

In [34]:
lr.score(x_test,y_test)       #unknown dataset

0.8382067650729107

In [35]:
# Let's create a function to create adjusted R-Squared 
def adj_r2(x,y): 
    r2=lr.score(x,y) 
    n = x.shape[0]
    p = x.shape[1]
    adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1) 
    return adjusted_r2

In [36]:
adj_r2(x_test,y_test)

0.8285268279405207

model_2-LASSO

In [37]:
lassocv = LassoCV(cv=10,max_iter=20000,normalize = True)
lassocv.fit(x_train,y_train)

LassoCV(cv=10, max_iter=20000, normalize=True)

In [38]:
lassocv.alpha_

6.4433702069018035e-06

In [39]:
lasso = Lasso(alpha=lassocv.alpha_)
lasso.fit(x_train,y_train)

Lasso(alpha=6.4433702069018035e-06)

In [40]:
lasso.score(x_test,y_test)

0.8382059458158139

model_3-RIDGE

In [41]:
ridgecv = RidgeCV(alphas = (0.1,1.0,10.0),cv = 10 , normalize =True)
ridgecv.fit(x_train,y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), cv=10, normalize=True)

In [42]:
ridgecv.alpha_

0.1

model_3-RIDGE_hypertune

In [43]:
ridge_lr = Ridge(alpha = ridgecv.alpha_)
ridge_lr.fit(x_train,y_train)

Ridge(alpha=0.1)

In [44]:
ridge_lr.score(x_test,y_test)

0.8382040214996789

model_4-ELASTICNET

In [45]:
elastic = ElasticNetCV(alphas= None,cv = 10)
elastic.fit(x_train,y_train)

ElasticNetCV(cv=10)

In [46]:
elastic.alpha_

0.0002526497859204946

In [47]:
elastic.l1_ratio_

0.5

model_5_ELASTICNET_hypertune

In [48]:
elastic_lr = ElasticNet(alpha=elastic.alpha_, l1_ratio= elastic.l1_ratio_)

In [49]:
elastic_lr.fit(x_train,y_train)

ElasticNet(alpha=0.0002526497859204946)

In [50]:
elastic_lr.score(x_test,y_test)

0.8382523816983748