In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import pickle
from pandas_profiling import ProfileReport
import numpy as np

In [2]:
df = pd.read_csv('Advertising.csv')

In [3]:
df

Unnamed: 0     TV  radio  newspaper  sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [4]:
df.describe()

Unnamed: 0          TV       radio   newspaper       sales
count  200.000000  200.000000  200.000000  200.000000  200.000000
mean   100.500000  147.042500   23.264000   30.554000   14.022500
std     57.879185   85.854236   14.846809   21.778621    5.217457
min      1.000000    0.700000    0.000000    0.300000    1.600000
25%     50.750000   74.375000    9.975000   12.750000   10.375000
50%    100.500000  149.750000   22.900000   25.750000   12.900000
75%    150.250000  218.825000   36.525000   45.100000   17.400000
max    200.000000  296.400000   49.600000  114.000000   27.000000

In [7]:
pf =ProfileReport(df)
pf.to_file('Linear regression.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [8]:
x = df[["TV"]]
x

TV
0    230.1
1     44.5
2     17.2
3    151.5
4    180.8
..     ...
195   38.2
196   94.2
197  177.0
198  283.6
199  232.1

[200 rows x 1 columns]

In [9]:
y = df.sales
y

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ... 
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: sales, Length: 200, dtype: float64

In [10]:
from sklearn.linear_model import LinearRegression
linear = LinearRegression()

In [11]:
linear.fit(x,y)

LinearRegression()

In [12]:
linear.intercept_

7.032593549127693

In [13]:
linear.coef_

array([0.04753664])

In [14]:
file = 'linear_reg.sav'
pickle.dump(linear,open(file,'wb'))


In [15]:
linear.predict([[45]])

array([9.17174237])

In [16]:
l = [4,5,6,7,89,34,45,67,23]
for i in l :
    print(linear.predict([[i]]))

[7.22274011]
[7.27027675]
[7.31781339]
[7.36535003]
[11.26335455]
[8.64883932]
[9.17174237]
[10.21754846]
[8.12593628]


In [17]:
def gd(x,y,n):
    m=6
    c=3
    alpha=0.8
    len=x.shape[0]
    for r in range(n):
        y_pred=m*x +c
        cost=(1/len)*((y_pred-y)**2).sum()
        print('cost is ',cost)
        m=m-(-alpha/len)*((y-y_pred)*x).sum()
        c=c-(-alpha/len)*((y-y_pred).sum())
        print('m,c is',m,c)
        if cost<1:
            plt.scatter(x,y)
            plt.plot(x,y_pred)

In [18]:
file = 'linear_reg.sav'
pickle.dump(linear,open(file,'wb'))

In [19]:
saved_model = pickle.load(open(file,'rb'))

In [20]:
saved_model.predict([[45]])

array([9.17174237])

In [21]:
linear.score(x,y)

0.611875050850071

In [22]:
data_x = df[['TV','radio','newspaper']]
data_x

TV  radio  newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [23]:
y = df.sales
y

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ... 
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: sales, Length: 200, dtype: float64

In [24]:
lm = LinearRegression()
lm.fit(data_x,y)

LinearRegression()

In [25]:
lm.score(data_x,y)

0.8972106381789522

In [26]:
import statsmodels.formula.api as smf
lm = smf.ols(formula='sales ~ TV',data=df).fit()
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.612
Model:                            OLS   Adj. R-squared:                  0.610
Method:                 Least Squares   F-statistic:                     312.1
Date:                Mon, 16 May 2022   Prob (F-statistic):           1.47e-42
Time:                        20:46:25   Log-Likelihood:                -519.05
No. Observations:                 200   AIC:                             1042.
Df Residuals:                     198   BIC:                             1049.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      7.0326      0.458     15.360      0.000       6.130       7.935
TV             0.0475      0.003     17.668      0.000       0.042       0.053
==============================================================================
Omnibus:                        0.531   Durbin-Watson:                   1.935
Prob(Omnibus):                  0.767   Jarque-Bera (JB):                0.669
Skew:                          -0.089   Prob(JB):                        0.716
Kurtosis:                       2.779   Cond. No.                         338.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""